DROP TRIGGER ar_did_delete_rooms ON rooms;
DROP TRIGGER ar_did_delete_rooms_students ON rooms_students;
DROP TRIGGER ar_did_delete_students ON students;
DROP TRIGGER ar_did_insert_rooms ON rooms;
DROP TRIGGER ar_did_insert_rooms_students ON rooms_students;
DROP TRIGGER ar_did_insert_students ON students;
DROP TRIGGER ar_did_update_rooms ON rooms;
DROP TRIGGER ar_did_update_rooms_students ON rooms_students;
DROP TRIGGER ar_did_update_students ON students;
